[package]
name = "cli_mini"
version = "0.1.0"
authors = ["empea-careercriminal <empeamtk@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2.10"
